# Site Settings
title:               SelfDotSend
tagline:             Message passing is just a Procedure Call.
description:
baseurl:             "/"
url:                 "https://selfdotsend.com"
enforce_ssl:         "www.selfdotsend.com"
github:
  url:               "https://selfdotsend.com"
author:
  name:              "Pankaj Doharey"
  email:             "[pankajdoharey][at][gmail][dot][com]"
  twitter:           "pankajdoharey"
  instagram:         ""
  github:            "metacritical"
  facebook:          ""
  linkedin:          ""
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              "Eshaiwastotallycrazyaboutyoubutnowihaveregainedsomesense"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:
  - jekyll-paginate
