# Site Settings
title:               SelfDotSend
tagline:             Message passing is just a Procedure Call.
description:
baseurl:            #"/"
url:                #"http://selfdotsend.com"
github:
  url:              #"https://metacritical.github.io"
author:
  name:              "Pankaj Doharey"
  email:             "[pankajdoharey][at][gmail][dot][com]"
  twitter:           "pankajdoharey"
  instagram:         ""
  github:            "metacritical"
  facebook:          ""
  linkedin:          ""
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
