#!/usr/bin/env python3
"""Generate the drafts index page from org files in drafts/.

Produces the same medium-post-card layout as the blog homepage.
"""
import re
import os
import sys
import html
from pathlib import Path

repo_dir = Path(sys.argv[1])
drafts_dir = repo_dir / "drafts"
public_dir = repo_dir / "public"
template_path = public_dir / "archiveorg" / "index.html"
output_path = public_dir / "drafts" / "index.html"

if not drafts_dir.is_dir():
    sys.exit(0)

MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

posts = []
for org_file in sorted(drafts_dir.glob("*.org")):
    content = org_file.read_text(encoding="utf-8", errors="replace")

    m_title = re.search(r'^#\+TITLE:\s+(.*)', content, re.MULTILINE)
    title = m_title.group(1).strip() if m_title else org_file.stem

    m_date = re.search(r'^#\+DATE:\s+\[?(\d{4})-(\d{2})-(\d{2})', content, re.MULTILINE)
    if m_date:
        year, month, day = int(m_date.group(1)), int(m_date.group(2)), int(m_date.group(3))
    else:
        year, month, day = 2018, 1, 1

    m_uri = re.search(r'^#\+URI:\s+(.*)', content, re.MULTILINE)
    if m_uri:
        uri = m_uri.group(1).strip()
        uri = uri.replace("%y", str(year)).replace("%m", f"{month:02d}").replace("%d", f"{day:02d}")
        uri = uri.rstrip("/") + "/"
    else:
        uri = f"/blog/{year}/{month:02d}/{day:02d}/{org_file.stem}/"

    m_desc = re.search(r'^#\+DESCRIPTION:\s+(.*)', content, re.MULTILINE)
    desc = m_desc.group(1).strip() if m_desc else ""

    m_tags = re.search(r'^#\+TAGS:\s+(.*)', content, re.MULTILINE)
    tags = [t.strip() for t in m_tags.group(1).split(",")] if m_tags else []

    # Preview URL: /drafts/<slug>/ (generated by build_draft_previews.py)
    slug = org_file.stem
    preview_url = f"/drafts/{slug}/"

    posts.append((year, month, day, title, preview_url, desc, tags, slug))

posts.sort(key=lambda p: (p[0], p[1], p[2]), reverse=True)

# Build card HTML matching the homepage medium-post-card layout.
cards = []
for year, month, day, title, preview_url, desc, tags, slug in posts:
    title_esc = html.escape(title)
    desc_esc = html.escape(desc) if desc else "No description yet."
    date_str = f"{MONTHS[month]} {day:02d}, {year}"
    tag_str = " ".join(f"<span class=\"medium-post-tag\">{html.escape(t)}</span>" for t in tags[:3])
    badge = '<span class="medium-post-draft-badge">Draft</span>'
    edit_link = f'<a class="medium-post-edit" href="/editor/?slug={slug}&kind=draft" title="Edit draft">Edit</a>'

    cards.append(f"""  <article class="medium-post-card">
    <a class="medium-post-main" href="{preview_url}">
      {badge}
      <h2>{title_esc}</h2>
      <p>{desc_esc}</p>
      <div class="medium-post-meta">{date_str}</div>
      <div class="medium-post-tags">{tag_str}</div>
    </a>
    <div class="medium-post-thumb-wrap">
      <a class="medium-post-thumb" href="{preview_url}">
        <img src="/media/images/placeholder.png" alt="Draft article">
      </a>
      {edit_link}
    </div>
  </article>""")

body_html = '<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:24px">'
body_html += '<div><h1 style="margin-bottom:4px">Drafts</h1>'
body_html += '<p style="color:#6f6a5e;font-size:14px">Work in progress — not yet published.</p></div>'
body_html += '<a href="/editor/" style="background:#36c9c7;color:#fff;padding:8px 18px;border-radius:6px;font-size:13px;font-weight:600;text-decoration:none">New Draft</a>'
body_html += '</div>\n'
body_html += """<style>
.medium-post-draft-badge{display:inline-block;font-size:10px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#8a8578;background:#e8e3d4;padding:2px 8px;border-radius:4px;margin-bottom:8px}
.medium-post-thumb-wrap{position:relative}
.medium-post-edit{position:absolute;bottom:8px;right:8px;background:rgba(31,31,27,.85);color:#fff;padding:3px 10px;border-radius:4px;font-size:11px;font-weight:600;text-decoration:none;letter-spacing:0}
.medium-post-tags{display:flex;gap:6px;margin-top:8px;flex-wrap:wrap}
.medium-post-tag{font-size:11px;color:#6f6a5e;background:#f1ece0;padding:2px 8px;border-radius:3px}
</style>
"""
body_html += '<section class="medium-home">\n'
body_html += "\n".join(cards)
body_html += '\n</section>'

if not template_path.exists():
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"<!DOCTYPE html><html><head><title>Drafts</title></head><body>{body_html}</body></html>",
        encoding="utf-8")
    print(f"Drafts page written to {output_path}")
    sys.exit(0)

template = template_path.read_text(encoding="utf-8", errors="replace")

# Use post-page wrapper (wider) instead of home (narrower).
result = re.sub(
    r'(<section[^>]*class="[^"]*post-page"[^>]*>\s*<div class="post">\s*)(.*?)(\s*</div>\s*</section>)',
    lambda m: m.group(1) + body_html.rstrip() + m.group(3),
    template,
    flags=re.DOTALL,
)

# Also try home wrapper as fallback.
if 'medium-home' not in result:
    result = re.sub(
        r'(<section[^>]*>\s*<div class="post">\s*)(.*?)(\s*</div>\s*</section>)',
        lambda m: m.group(1) + body_html.rstrip() + m.group(3),
        template,
        flags=re.DOTALL,
    )

# Fix the page title.
result = result.replace("<title>Archive", "<title>Drafts")
result = result.replace('class="home"', 'class="post-page"')

output_path.parent.mkdir(parents=True, exist_ok=True)
output_path.write_text(result, encoding="utf-8")
print(f"Drafts page written to {output_path}")
